version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: proproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/proproject
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: python run.py

volumes:
  postgres_data: