version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    networks:
      - webnet

  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - webnet

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - webnet

volumes:
  pgdata:

networks:
  webnet:
    driver: bridge
