"""Add AI assistant settings fields

Revision ID: 4d53b6a79454
Revises: cabd280c39d5
Create Date: 2025-09-21 18:39:17.229742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d53b6a79454'
down_revision = 'cabd280c39d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ai_assistant_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_model_preference', sa.String(length=50), nullable=False, server_default='gpt-3.5-turbo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_model_preference')
        batch_op.drop_column('ai_assistant_enabled')
        batch_op.drop_column('openai_api_key')

    # ### end Alembic commands ###
