"""Add AI assistant settings with defaults

Revision ID: 5c69053ed761
Revises: cabd280c39d5
Create Date: 2025-09-21 18:41:01.929866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c69053ed761'
down_revision = 'cabd280c39d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_access_token', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('google_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_connected', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ai_assistant_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_model_preference', sa.String(length=50), nullable=False, server_default='gpt-3.5-turbo'))
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.drop_column('ai_model_preference')
        batch_op.drop_column('ai_assistant_enabled')
        batch_op.drop_column('openai_api_key')
        batch_op.drop_column('google_calendar_connected')
        batch_op.drop_column('google_token_expires_at')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
